from django.db import models

# Create your models here.

class GhoshVargRegister(models.Model):
    ghosh_varg_register_id = models.BigAutoField(primary_key=True)
    name = models.TextField()
    last_name = models.TextField(blank=False, null=True)
    dob = models.DateField()
    phone_number = models.TextField()
    gender = models.TextField()
    blood_group = models.TextField(blank=False, null=True)
    corress_address = models.TextField(blank=False, null=True)
    perman_address = models.TextField(blank=True, null=True)
    address_pincode = models.TextField(blank=True, null=True)
    address_state = models.TextField(blank=True, null=True)
    ekai_sakha_milan = models.TextField(blank=True, null=True)
    ekai_milaan = models.TextField(blank=True, null=True)
    nagar_address = models.TextField(blank=True, null=True)
    pincode = models.TextField()
    user_type = models.TextField(blank=True, null=True)
    ekai_mandal = models.TextField(blank=True, null=True)
    referral_code = models.CharField(max_length=255, default='1925')
    responsibility_yes_no = models.TextField(blank=True, null=True)
    vividhsangathan = models.TextField(blank=True, null=True)
    ekai_basti = models.TextField(blank=True, null=True)
    state = models.TextField(blank=True, null=True)
    ekai_upbasti = models.TextField(blank=True, null=True)
    ekai = models.TextField(blank=True, null=True)
    ekai_nagar = models.TextField(blank=True, null=True)
    dayitv = models.TextField(blank=True, null=True)
    nagar = models.TextField(blank=True, null=True)
    prant = models.TextField(blank=True, null=True)
    vibhag = models.TextField(blank=True, null=True)
    jila = models.TextField(blank=True, null=True)
    ekai_sangh_shikshan_level = models.TextField(blank=True, null=True)
    pratigya = models.TextField(blank=True, null=True)
    prarambhik_varsh = models.TextField(blank=True, null=True)
    prathmik_varsh = models.TextField(blank=True, null=True)
    pratham_varsh = models.TextField(blank=True, null=True)
    dwitiya_varsh = models.TextField(blank=True, null=True)
    tritiya_varsh = models.TextField(blank=True, null=True)
    ghosh_vadak = models.TextField(blank=True, null=True)
    shankh = models.TextField(blank=True, null=True)
    shrung = models.TextField(blank=True, null=True)
    turya = models.TextField(blank=True, null=True)
    swarad = models.TextField(blank=True, null=True)
    nagang = models.TextField(blank=True, null=True)
    gomukh = models.TextField(blank=True, null=True)
    other = models.TextField(blank=True, null=True)
    aanak = models.TextField(blank=True, null=True)
    panav = models.TextField(blank=True, null=True)
    jhallari = models.TextField(blank=True, null=True)
    tribhuj = models.TextField(blank=True, null=True)
    shankh_shrung_own = models.TextField(blank=True, null=True)
    rachnaye = models.TextField(blank=True, null=True)
    learn_vadya = models.TextField(blank=True, null=True)
    learn_vadya_list = models.TextField(blank=True, null=True)
    sanghpant = models.TextField(blank=True, null=True)
    whiteshirt = models.TextField(blank=True, null=True)
    sanghtopi = models.TextField(blank=True, null=True)
    sanghpeti = models.TextField(blank=True, null=True)
    jurab = models.TextField(blank=True, null=True)
    joote = models.TextField(blank=True, null=True)
    dand = models.TextField(blank=True, null=True)
    shiksha = models.TextField(blank=True, null=True)
    aarthik = models.TextField(blank=True, null=True)
    dharmik = models.TextField(blank=True, null=True)
    samajik = models.TextField(blank=True, null=True)
    seva = models.TextField(blank=True, null=True)
    swasthya = models.TextField(blank=True, null=True)
    sanskritik = models.TextField(blank=True, null=True)
    vaicharik = models.TextField(blank=True, null=True)
    suraksha = models.TextField(blank=True, null=True)
    media = models.TextField(blank=True, null=True)
    affilated_by = models.TextField(blank=True, null=True)
    institute_name = models.TextField(blank=True, null=True)
    category_name = models.TextField(blank=True, null=True)
    profession_subtype = models.TextField(blank=True, null=True)
    profession_type = models.TextField(blank=True, null=True)
    industrialist_type = models.TextField(blank=True, null=True)
    industrialist_sub_type = models.TextField(blank=True, null=True)
    student_type = models.TextField(blank=True, null=True)
    college_student_type = models.TextField(blank=True, null=True)
    social_work_area = models.TextField(blank=True, null=True)
    teacher_type = models.TextField(blank=True, null=True)
    business_type = models.TextField(blank=True, null=True)
    business_sub_type = models.TextField(blank=True, null=True)
    rss_association = models.TextField(blank=True, null=True)
    activity = models.TextField(blank=True, null=True)
    updated_on = models.DateTimeField(auto_now=True)

    class Meta:
        db_table = 'ghosh_varg_registration'

