# Generated by Django 5.1.6 on 2025-02-11 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BarcodeScan',
            fields=[
                ('barcode_scan_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=255)),
                ('nagar', models.CharField(max_length=255)),
                ('dayitv', models.CharField(max_length=255)),
                ('qrcode', models.CharField(max_length=255)),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'barcode_scan',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DayitvMaster',
            fields=[
                ('dayitv_id', models.AutoField(primary_key=True, serialize=False)),
                ('dayitv_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'dayitv_master',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EkaiMaster',
            fields=[
                ('ekai_id', models.AutoField(primary_key=True, serialize=False)),
                ('ekai_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'ekai_master',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NagarMaster',
            fields=[
                ('nagar_id', models.AutoField(primary_key=True, serialize=False)),
                ('nagar_name', models.CharField(max_length=255)),
                ('nagar_hindi', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'nagar_master',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PincodeMaster',
            fields=[
                ('pincode_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('pincode', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('nagar', models.CharField(blank=True, max_length=255, null=True)),
                ('nagar_hindi', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'pincode_master',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PrantMaster',
            fields=[
                ('prant_id', models.AutoField(primary_key=True, serialize=False)),
                ('prant_name', models.CharField(max_length=255)),
                ('prant_hindi', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'prant_master',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProfessionMaster',
            fields=[
                ('profession_id', models.AutoField(primary_key=True, serialize=False)),
                ('profession_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'profession_master',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RegisterSamautkarshOtp',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('mobile', models.CharField(max_length=10)),
                ('otp', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'register_samautkarsh_otp',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RegisterSamautkarshRegistration',
            fields=[
                ('register_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('dob', models.DateField()),
                ('phone_number', models.CharField(max_length=255, unique=True)),
                ('gender', models.CharField(max_length=255)),
                ('corress_address', models.TextField(blank=True, null=True)),
                ('perman_address', models.TextField(blank=True, null=True)),
                ('nagar_address', models.TextField(blank=True, null=True)),
                ('pincode', models.TextField()),
                ('user_type', models.CharField(max_length=255)),
                ('other_user_type', models.CharField(blank=True, max_length=255, null=True)),
                ('referral_code', models.CharField(max_length=255)),
                ('vividhsangathan', models.CharField(blank=True, max_length=255, null=True)),
                ('other_vividhsangathan_name', models.CharField(blank=True, db_column='other_vividhSangathan_name', max_length=255, null=True)),
                ('state', models.CharField(blank=True, max_length=255, null=True)),
                ('other_state_name', models.CharField(blank=True, max_length=255, null=True)),
                ('ekai', models.CharField(blank=True, max_length=255, null=True)),
                ('ekai_nagar', models.CharField(blank=True, max_length=255, null=True)),
                ('dayitv', models.CharField(blank=True, max_length=255, null=True)),
                ('other_dayitv_name', models.CharField(blank=True, max_length=255, null=True)),
                ('updated_on', models.DateTimeField()),
            ],
            options={
                'db_table': 'register_samautkarsh_registration',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RegisterSamautkarshUser',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('mobile', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'register_samautkarsh_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VibhagMaster',
            fields=[
                ('vibhag_id', models.AutoField(primary_key=True, serialize=False)),
                ('vibhag_name', models.CharField(max_length=255)),
                ('vibhag_hindi', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'vibhag_master',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Vividhsanghthan',
            fields=[
                ('vividhsangathan_id', models.AutoField(primary_key=True, serialize=False)),
                ('vividhsangathan_name', models.CharField(db_column='vividhSangathan_name', max_length=255)),
                ('referral_code', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'vividhsanghthan',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ZilaMaster',
            fields=[
                ('jila_id', models.AutoField(primary_key=True, serialize=False)),
                ('jila_name', models.CharField(max_length=255)),
                ('jila_hindi', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'zila_master',
                'managed': False,
            },
        ),
    ]
