# Generated by Django 5.1.5 on 2025-01-31 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register_samautkarsh', '0006_dayitvmaster_delete_dayitv_delete_nagardaytivmaster_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BarcodeScan',
            fields=[
                ('barcode_scan_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('nagar', models.CharField(max_length=255)),
                ('dayitv', models.CharField(max_length=255)),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'barcode_scan',
                'managed': False,
            },
        ),
    ]
