# Generated by Django 5.1.5 on 2025-02-06 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register_samautkarsh', '0009_alter_user_mobile'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterSamautkarshOtp',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('mobile', models.CharField(max_length=10)),
                ('otp', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'register_samautkarsh_otp',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RegisterSamautkarshUser',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('mobile', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'register_samautkarsh_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Vividhsanghthan',
            fields=[
                ('vividhsangathan_id', models.AutoField(primary_key=True, serialize=False)),
                ('vividhsangathan_name', models.CharField(db_column='vividhSangathan_name', max_length=255)),
                ('referral_code', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'vividhsanghthan',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='OTP',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
