# Generated by Django 5.1.5 on 2025-01-23 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register_samautkarsh', '0004_alter_registersamautkarshregistration_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='registersamautkarshregistration',
            table='register_samautkarsh_registration',
        ),
    ]
