# Generated by Django 5.2 on 2025-04-07 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner_admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BarcodeScan',
            fields=[
                ('barcode_scan_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=255)),
                ('nagar', models.CharField(max_length=255)),
                ('dayitv', models.CharField(max_length=255)),
                ('qrcode', models.CharField(max_length=255)),
                ('status', models.CharField(default='pending', max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('Approving_person', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'barcode_scan',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BastiMaster',
            fields=[
                ('basti_id', models.AutoField(primary_key=True, serialize=False)),
                ('basti_name', models.CharField(max_length=255)),
                ('basti_hindi', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'basti_master',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DayitvMaster',
            fields=[
                ('dayitv_id', models.AutoField(primary_key=True, serialize=False)),
                ('dayitv_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'dayitv_master',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EkaiMaster',
            fields=[
                ('ekai_id', models.AutoField(primary_key=True, serialize=False)),
                ('ekai_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'ekai_master',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MandalMaster',
            fields=[
                ('mandal_id', models.AutoField(primary_key=True, serialize=False)),
                ('mandal_name', models.CharField(max_length=255)),
                ('mandal_hindi', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'mandal_master',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NagarMaster',
            fields=[
                ('nagar_id', models.AutoField(primary_key=True, serialize=False)),
                ('nagar_name', models.CharField(max_length=255)),
                ('nagar_hindi', models.TextField(max_length=255)),
            ],
            options={
                'db_table': 'nagar_master',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PincodeMaster',
            fields=[
                ('pincode_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('pincode', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('nagar', models.CharField(blank=True, max_length=255, null=True)),
                ('nagar_hindi', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'pincode_master',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PrantMaster',
            fields=[
                ('prant_id', models.AutoField(primary_key=True, serialize=False)),
                ('prant_name', models.CharField(max_length=255)),
                ('prant_hindi', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'prant_master',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProfessionMaster',
            fields=[
                ('profession_id', models.AutoField(primary_key=True, serialize=False)),
                ('profession_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'profession_master',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RegisterSamautkarshOtp',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('mobile', models.CharField(max_length=10)),
                ('otp', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'register_samautkarsh_otp',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RegisterSamautkarshRegistration',
            fields=[
                ('register_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('dob', models.DateField()),
                ('phone_number', models.CharField(max_length=255, unique=True)),
                ('gender', models.CharField(max_length=255)),
                ('corress_address', models.TextField(blank=True, null=True)),
                ('perman_address', models.TextField(blank=True, null=True)),
                ('nagar_address', models.TextField(blank=True, null=True)),
                ('pincode', models.TextField()),
                ('user_type', models.CharField(max_length=255)),
                ('ekai_mandal', models.CharField(blank=True, max_length=255, null=True)),
                ('referral_code', models.CharField(max_length=255)),
                ('vividhsangathan', models.CharField(blank=True, max_length=255, null=True)),
                ('ekai_basti', models.CharField(blank=True, max_length=255, null=True)),
                ('state', models.CharField(blank=True, max_length=255, null=True)),
                ('ekai_upbasti', models.CharField(blank=True, max_length=255, null=True)),
                ('ekai', models.CharField(blank=True, max_length=255, null=True)),
                ('ekai_nagar', models.CharField(blank=True, max_length=255, null=True)),
                ('dayitv', models.CharField(blank=True, max_length=255, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'register_samautkarsh_registration',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RegisterSamautkarshUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(max_length=15, unique=True)),
            ],
            options={
                'db_table': 'register_samautkarsh_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ScannedPerson',
            fields=[
                ('scanned_people_id', models.AutoField(primary_key=True, serialize=False)),
                ('phone_number', models.CharField(max_length=255, null=True, unique=True)),
                ('person_scanned', models.CharField(max_length=255, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'scanned_people',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UpbastiMaster',
            fields=[
                ('upbasti_id', models.AutoField(primary_key=True, serialize=False)),
                ('upbasti_name', models.CharField(max_length=255)),
                ('upbasti_hindi', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'upbasti_master',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VibhagMaster',
            fields=[
                ('vibhag_id', models.AutoField(primary_key=True, serialize=False)),
                ('vibhag_name', models.CharField(max_length=255)),
                ('vibhag_hindi', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'vibhag_master',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Vividhsanghthan',
            fields=[
                ('vividhsangathan_id', models.AutoField(primary_key=True, serialize=False)),
                ('vividhsangathan_name', models.CharField(db_column='vividhSangathan_name', max_length=255)),
                ('referral_code', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'vividhsanghthan',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ZilaMaster',
            fields=[
                ('jila_id', models.AutoField(primary_key=True, serialize=False)),
                ('jila_name', models.CharField(max_length=255)),
                ('jila_hindi', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'zila_master',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=15, null=True, unique=True)),
                ('role', models.CharField(max_length=255, null=True)),
                ('role_level', models.CharField(max_length=255, null=True)),
                ('role_sublevel', models.CharField(max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='QRCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField()),
                ('scanned_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
