# Generated by Django 5.1.5 on 2025-01-23 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register_samautkarsh', '0003_alter_registersamautkarshregistration_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registersamautkarshregistration',
            options={'managed': False},
        ),
    ]
