# Generated by Django 5.1.5 on 2025-01-29 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register_samautkarsh', '0005_alter_registersamautkarshregistration_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='DayitvMaster',
            fields=[
                ('dayitv_id', models.AutoField(primary_key=True, serialize=False)),
                ('dayitv_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'dayitv_master',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Dayitv',
        ),
        migrations.DeleteModel(
            name='NagarDaytivMaster',
        ),
        migrations.DeleteModel(
            name='PrantDaytivMaster',
        ),
        migrations.DeleteModel(
            name='QualificationMaster',
        ),
        migrations.DeleteModel(
            name='VibhagDaytivMaster',
        ),
        migrations.DeleteModel(
            name='ZilaDaytivMaster',
        ),
        migrations.AlterModelTable(
            name='pincodemaster',
            table='pincode_master',
        ),
    ]
