# Generated by Django 5.1.5 on 2025-02-10 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register_samautkarsh', '0010_registersamautkarshotp_registersamautkarshuser_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RegisterSamautkarshOtp',
        ),
        migrations.DeleteModel(
            name='RegisterSamautkarshUser',
        ),
    ]
