# Generated by Django 5.1.5 on 2025-01-21 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Dayitv',
            fields=[
                ('dayitv_id', models.AutoField(primary_key=True, serialize=False)),
                ('daytiv_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'dayitv',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EkaiMaster',
            fields=[
                ('ekai_id', models.AutoField(primary_key=True, serialize=False)),
                ('ekai_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'ekai_master',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NagarDaytivMaster',
            fields=[
                ('nagar_daytiv_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'nagar_daytiv_master',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NagarMaster',
            fields=[
                ('nagar_id', models.AutoField(primary_key=True, serialize=False)),
                ('nagar_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'nagar_master',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PincodeMaster',
            fields=[
                ('pincode_id', models.AutoField(primary_key=True, serialize=False)),
                ('pincode', models.BigIntegerField()),
                ('area', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Pincode_master',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PrantDaytivMaster',
            fields=[
                ('prant_daytiv_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'prant_daytiv_master',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PrantMaster',
            fields=[
                ('prant_id', models.AutoField(primary_key=True, serialize=False)),
                ('prant_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'prant_master',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProfessionMaster',
            fields=[
                ('profession_id', models.AutoField(primary_key=True, serialize=False)),
                ('profession_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'profession_master',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='QualificationMaster',
            fields=[
                ('qualification_id', models.AutoField(primary_key=True, serialize=False)),
                ('qualification_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'qualification_master',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VibhagDaytivMaster',
            fields=[
                ('vibhag_daytiv_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'vibhag_daytiv_master',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VibhagMaster',
            fields=[
                ('vibhag_id', models.AutoField(primary_key=True, serialize=False)),
                ('vibhag_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'vibhag_master',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ZilaDaytivMaster',
            fields=[
                ('zila_daytiv_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'zila_daytiv_master',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ZilaMaster',
            fields=[
                ('zila_id', models.AutoField(primary_key=True, serialize=False)),
                ('zila_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'zila_master',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=15)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('address', models.TextField()),
                ('nagar', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=6)),
                ('user_type', models.CharField(choices=[('Basic', 'Basic'), ('Premium', 'Premium')], max_length=10)),
                ('referral_code', models.CharField(choices=[('Code1', 'Referral Code 1'), ('Code2', 'Referral Code 2'), ('Code3', 'Referral Code 3')], max_length=10)),
            ],
        ),
    ]
