# Generated by Django 5.1.5 on 2025-01-23 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register_samautkarsh', '0002_registersamautkarshregistration_delete_registration'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registersamautkarshregistration',
            options={},
        ),
        migrations.AlterModelTable(
            name='registersamautkarshregistration',
            table=None,
        ),
    ]
