# Generated by Django 5.1.5 on 2025-01-23 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register_samautkarsh', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterSamautkarshRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=15, unique=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=10)),
                ('corress_address', models.TextField()),
                ('perman_address', models.TextField()),
                ('nagar', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=6)),
                ('user_type', models.CharField(choices=[('A', 'Type A'), ('B', 'Type B')], max_length=50)),
                ('referral_code', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'register_samautkarsh_registration',
                'managed': True,
            },
        ),
        migrations.DeleteModel(
            name='Registration',
        ),
    ]
