# Generated by Django 5.1.4 on 2025-02-05 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register_samautkarsh', '0008_otp_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mobile',
            field=models.CharField(max_length=10),
        ),
    ]
